
version: '3.8'

services:
  filebrowser:
    image: nginx:alpine
    container_name: filebrowser-nginx
    volumes:
      - ./srv:/usr/share/nginx/html:ro
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/auth:/etc/nginx/auth:ro
    environment:
      - SERVICE_FQDN=filebrowser.csa.ps
    restart: unless-stopped
